### ISSUE TITLE
Unable to download webpage: HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by Hanqer** [rocksyne/kinetics-dataset-downloader#1]
Unable to download webpage: HTTP Error 429: Too Many Requests when start downloading.

**Comment by rocksyne** [comment]
@Hanqer please follow this discussion at [https://askubuntu.com/a/1243665/1153669](https://askubuntu.com/a/1243665/1153669). On line 281 of KineticsDatasetManager.py

ammend 
`os.system("ffmpeg "+self.show_log_cmd+" -ss "+start_time+" -i $(youtube-dl -f 18 --get-url "+youtube_link+") -t 10 -c:v copy -c:a copy '"+vid_path+"'")`

to 

`os.system("ffmpeg "+self.show_log_cmd+" -ss "+start_time+" -i $(youtube-dl -f 18 --force-ipv4 --get-url "+youtube_link+") -t 10 -c:v copy -c:a copy '"+vid_path+"'")`

Add  --force-ipv4 to the youtube-dl call to force the use of ipv4. I hope this helps.
