### ISSUE TITLE
Crawler isn't downloading videos

### ISSUE THREAD

**Issue by preetshah7** [rocksyne/kinetics-dataset-downloader#2]
![Screenshot (339)](https://user-images.githubusercontent.com/63279310/135743220-b65518e6-7ac8-4286-8baa-7ea171b671b8.png)

As you can see all the class directories are empty, even though the crawler ran for 10 minutes. This is the command line instance for your reference. Please help me out.
```
(base) C:\Users\zeels\Desktop\Vigilance AI\kinetics-dataset-downloader>python kinetics_dataset.py -v 700 -t train -d vigilance

Destination path '<vigilance\train>' was created successfully!


List of classes available in Kinetics700 train split dataset
------------------------------------------------------------------
1. DRINKING SHOTS (795 videos)
2. EATING BURGER (951 videos)
3. EATING CAKE (985 videos)
4. EATING CARROTS (624 videos)
5. EATING CHIPS (859 videos)
6. EATING DOUGHNUTS (823 videos)
7. EATING HOTDOG (784 videos)
8. EATING ICE CREAM (984 videos)
9. EATING NACHOS (652 videos)
10. EATING SPAGHETTI (988 videos)
11. EATING WATERMELON (735 videos)

Please choose a range of the dataset classes you want to download, eg. 1 or 1-11: 1-11

Downloading videos from class 'drinking shots' to 'eating watermelon'
100%|██████████████████████████████████████████████████████████████████████████████| 9180/9180 [11:18<00:00, 13.53it/s]

(base) C:\Users\zeels\Desktop\Vigilance AI\kinetics-dataset-downloader>
```

**Comment by niyatisrivastava** [comment]
same issue

**Comment by rocksyne** [comment]
> same issue

Youtube videos are public videos. They can be removed by the content owner or be restricted to a geographical location only. This morning, I tested the script in Eastern Europe and it works fine. Occasionally I get messages such as `This video contains content from SME, who has blocked it in your country on copyright grounds` or `Unable to extract video title` but most videos download. I tested the `ZUMA` videos in the `validate` set and was able to get 36 out of 42 videos. If you have a VPN, you could set your traffic origin from Europe or South Korea and see how that helps.
